server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: user-center
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql//localhost:3306/user-center
    username: root
    password: root
# 日志配置
knife4j:
  enable: true
  openapi:
    title: 用户中心接口文档
    version: 1.0
    group:
      test1:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.lc.usercenter.controller



